// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcEomEHQWISYxbCeZonsGTuUwLZcMJbVQ',
    appId: '1:951014375841:web:faa25becc8d59474e8cbe0',
    messagingSenderId: '951014375841',
    projectId: 'habit-tracker-7e2a3',
    authDomain: 'habit-tracker-7e2a3.firebaseapp.com',
    storageBucket: 'habit-tracker-7e2a3.firebasestorage.app',
    measurementId: 'G-K4V1JKC5VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo7Gc6eH7LgYU5gDfPb659aSzNwhiVEAk',
    appId: '1:951014375841:android:58d2c7963f40c450e8cbe0',
    messagingSenderId: '951014375841',
    projectId: 'habit-tracker-7e2a3',
    storageBucket: 'habit-tracker-7e2a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUHhBohZruE71e1-_jJCAsCMsrT5WHMYY',
    appId: '1:951014375841:ios:0e58a341e6dde443e8cbe0',
    messagingSenderId: '951014375841',
    projectId: 'habit-tracker-7e2a3',
    storageBucket: 'habit-tracker-7e2a3.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUHhBohZruE71e1-_jJCAsCMsrT5WHMYY',
    appId: '1:951014375841:ios:0e58a341e6dde443e8cbe0',
    messagingSenderId: '951014375841',
    projectId: 'habit-tracker-7e2a3',
    storageBucket: 'habit-tracker-7e2a3.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcEomEHQWISYxbCeZonsGTuUwLZcMJbVQ',
    appId: '1:951014375841:web:9d8349535da8ec4be8cbe0',
    messagingSenderId: '951014375841',
    projectId: 'habit-tracker-7e2a3',
    authDomain: 'habit-tracker-7e2a3.firebaseapp.com',
    storageBucket: 'habit-tracker-7e2a3.firebasestorage.app',
    measurementId: 'G-MQK9PYE1PZ',
  );
}
